### ISSUE TITLE
Inquiry: is this setup for multiple react projects?

### ISSUE THREAD

**Issue by dougmorin** [renderbox/django-react-tools#1]
In your documentation you have this set for one project root, if I turn this into a tuple or dict will it account for all projects?

**Comment by renderbox** [comment]
Not yet.  Did you find a work around?

**Comment by dougmorin** [comment]
None of the projects I found really worked well.  Some tried to run their own versions of create-react-app, some wanted just simple react scripts hosted in one file.  I found that none of these worked the way I wanted.  You should just be able to create a react project somewhere, include the build files and be able to add them to your site through the template.

I ended up creating a /react/ folder in my root, and added the build/static/ folder to my static dirs folder.

I then ended up writing a global function that would accept a string, which was the title of the folder the react project was in, and it would read the asset manifest and return the files that needed to be included in the template.  

From there I only needed to create a template file to accept the react project.

Worked like a charm.

**Comment by renderbox** [comment]
Cool,

I'm curious, what did you do differently from django-react-tools?  The tool I wrote takes a root react directory, builds the files and copies over the result into the static directory based on the manifest.  The idea is to run that command and then collect static when deploying.  It was done this way so the React App that was created was also committed with the Django project and (hopefully) stays in sync.

Were you looking to do this without Django?  I'm just asking since I'm always looking to improve the toolset.
